fix: send null instead of empty string when describing default client quotas (#3128)
DescribeClientQuota currently fails with the following error message
logged by the Kafka broker when trying to describe default client
quotas:
```
org.apache.kafka.common.errors.InvalidRequestException: Request specified MATCH_TYPE_DEFAULT, but also specified a match string
```
This is because we are currently sending an empty string (`""`) instead
of a null as the match string

The Java client simply ignores the match string here to avoid this
issue, so I propose we do the same
https://github.com/apache/kafka/blob/3ed590288fd773902f7791959e8f081ff937c144/clients/src/main/java/org/apache/kafka/common/requests/DescribeClientQuotasRequest.java#L54-L55

---------

Signed-off-by: Peter Dannemann <pdannemann@twilio.com>