fix: prevent race in asyncProducer retryHandler (#3733)
There is a potential race in the `asyncProducer` `retryHandler` which is
occasionally causing `nil` pointer dereferences on our side:

```
WARNING: DATA RACE
Write at 0x00c0001cd4d0 by goroutine 10:
  github.com/IBM/sarama.TestRetryHandlerHeadersRace.func2()
      /Users/dbl/src/github.com/IBM/sarama/async_producer_race_test.go:25 +0x18c

Previous read at 0x00c0001cd4d0 by goroutine 9:
  github.com/IBM/sarama.(*ProducerMessage).ByteSize()
      /Users/dbl/src/github.com/IBM/sarama/async_producer.go:400 +0x40
  github.com/IBM/sarama.(*asyncProducer).retryHandler()
      /Users/dbl/src/github.com/IBM/sarama/async_producer.go:1614 +0x488
  github.com/IBM/sarama.TestRetryHandlerHeadersRace.func1()
      /Users/dbl/src/github.com/IBM/sarama/async_producer_race_test.go:18 +0x68
```

`retryHandler` publishes a message to `p.input` and then reads it again
to update its `ByteSize`:

```go
case p.input <- buf.Peek():
    msgToRemove := buf.Remove()
    currentByteSize -= int64(msgToRemove.ByteSize(version))
```

Once that send completes the message belongs to `dispatcher`, which can
write to `Headers` through a `headerInterceptor`.

Only reachable with `Version >= V0_11_0_0` (`version == 2`): below that
`ByteSize` skips the `Headers` loop entirely.

**I've added a test to reproduce:**
```
go test -race -run TestRetryHandlerHeadersRace
```

**Output without the fix:**
```
[..]
--- FAIL: TestRetryHandlerHeadersRace (0.00s)
    testing.go:1617: race detected during execution of test
FAIL
exit status 1
FAIL	github.com/IBM/sarama	0.072s
```

**Output with the fix applied:**
```
PASS
ok  	github.com/IBM/sarama	1.082s
```

---------

Signed-off-by: Daniel Lobl <daniel.lobl@shopify.com>
Signed-off-by: Dominic Evans <dominic.evans@uk.ibm.com>
Co-authored-by: Dominic Evans <dominic.evans@uk.ibm.com>