fix: set min-go-version to 1.16
Changes that were introduced in 8ccea19c0cec5d05ed99068d46bf46efc900d24d
made it impossible to compile sarama with go 1.15
(which is mentioned as officially supported version in the README file)

io.Discard and io.ReadAll appeared only in 1.16
https://golang.org/doc/go1.16#ioutil

To address this issue this commit bumps minimal supported go version
defined in go.mod file, to provide a clear message that 1.16 is required

```
> go build
./config.go:678:37: undefined: io.Discard
./decompress.go:43:10: undefined: io.ReadAll
./decompress.go:55:10: undefined: io.ReadAll
./sarama.go:89:29: undefined: io.Discard
note: module requires Go 1.16
```