fix(protocol): add tagged field to alter configs config entries
ClusterAdmin.AlterConfig(...) against Kafka 3.8 results in the following
appearing in the broker logs:
```
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: ALTER_CONFIG
...
Caused by: java.lang.RuntimeException: Error reading byte array of 101 byte(s): only 74 byte(s) available
...
```

This can be worked around by switching to version 1 of the response
(versions earlier than V2_8_0_0), which disables the use of flexible
versions.

Comparing the Sarama implementation against Kafka's generated
`AlterConfigsRequestData.java` shows that the Kafka implementation adds
tagged fields after each `AlterableConfig` (config name/value pair).

Signed-off-by: Adrian Preston <PRESTONA@uk.ibm.com>